name: Create Archive
on: 
 push:
    branches: [ "main" ]
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
#     - name: Archive Release
#       uses: thedoctor0/zip-release@0.7.1
#       with:
#         type: 'zip'
#         filename: 'release.zip'
#         path: .
#         exclusions: '*.git*'
        
    - uses: vimtor/action-zip@v1
      with:
          files: ${{github.workspace}}
          dest: result-${{ github.sha }}.zip
        
        
#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.FULL_ACCESS }}
