name: Create Archive
on: 
 push:
    branches: [ "main" ]
 workflow_dispatch:
permissions:
  contents: write
  id-token: write
env:
 Filename: ${{ github.workspace }}/test1
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: main
    - name: Create local changes
      run: |
        rm -r Result
        cat ${{ github.workspace }}/test1
        sed -i 's|flow|new-flow|' ${{ env.Filename }}
        mkdir Result
        zip Result/result1.zip ${{ github.workspace }}/* -x "*.git*"
        cat ${{ github.workspace }}/test1
        ls -lrt
    - name: Commit & Push changes to same repo
      run: |
       cat ${{ github.workspace }}/test1
    - uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: 'Auto commit from github action test1'
        
        
    - name: Pushes to Repository
      uses: tech-thinker/push-to-repo@main
      env:
       API_TOKEN_GITHUB: ${{ secrets.MAVEN_TOKEN }}
      with:
       user-name: "github-actions[bot]"
       user-email: github-actions[bot]@users.noreply.github.com
       source-directory: "Result/result1.zip"
       destination-github-username: "kjs2021"
       destination-repository-name: "maven"
       target-branch: test-branch
    
#     - name: Pushes test file
#       uses: dmnemec/copy_file_to_another_repo_action@main
#       env:
#         API_TOKEN_GITHUB: ${{ secrets.MAVEN_TOKEN }}
#       with:
#         source_file: 'Result/result1.zip'
#         destination_repo: 'kjs2021/maven'
#         destination_folder: 'dev'
#         destination_branch: test-branch
#         user_email: 'kksaini6@yahoo.com'
#         user_name: 'kjs2021'
#         commit_message: 'A custom message for the commit'   
        
        
        
        
        
        
#     - name: Pushes to another repository
#       uses: cpina/github-action-push-to-another-repository@main
#       env:
# #           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
#           API_TOKEN_GITHUB: ${{ secrets.MAVEN_TOKEN }}
#       with:
#           source-directory: 'Result'
#           destination-github-username: 'kjs2021'
#           destination-repository-name: 'maven'
# #           user-email: carles3@pina.cat
#           target-branch: push
#           commit-message: " auto commit from ${{ env.Filename }}"
        
        
#     - name: Commit & Push changes to maven repo
#       run: |
#         cat ${{ github.workspace }}/test1
#         ls -lrt
#     - uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.MAVEN_TOKEN }}
#         branch: main
#         message: 'Auto commit from github ziptest repo action'
#         directory: ./devs
#         repository: kjs2021/maven
  
  
  
  
  
  
  
  
  
  
  

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@master
#        with:
#         persist-credentials: false 
#         fetch-depth: 0 
#      - run: |
#         cat ${{ github.workspace }}/test1
#         sed -i 's|action|flow|' ${{ github.workspace }}/test1
#         zip result.zip ${{ github.workspace }}/*
#         cat ${{ github.workspace }}/test1
#         ls -lrt
      
#       - name: Commit & Push changes
#         uses: actions-js/push@master
#         with:
#            github_token: ${{ secrets.GITHUB_TOKEN }}
#            branch: main
#            message: 'Auto commit from github action'
      
# #     - name: Archive Release
#       uses: thedoctor0/zip-release@0.7.1
#       with:
#         type: 'zip'
#         filename: 'release.zip'
#         path: .
#         exclusions: '*.git*'

        
#     - uses: vimtor/action-zip@v1
#       with:
#           files: ${{github.workspace}}
#           dest: result-${{ github.sha }}.zip
#     - name: push
#       uses: actions-x/commit@v6
        
        
#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.FULL_ACCESS }}
