name: Create Archive
on: 
 push:
    branches: [ "main" ]
 workflow_dispatch:
permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
       cat ${{ github.workspace }}/test1
       sed -i 's|action|flow|' ${{ github.workspace }}/test1
       zip result.zip ${{ github.workspace }}/*
       cat ${{ github.workspace }}/test1
       ls -lrt
       git config  user.email kksaini6@yahoo.com
       git config  user.name   ${{ github.repository_owner }}
       git add .
       git commit -m "auto commit "
       git push origin 
#     - name: Archive Release
#       uses: thedoctor0/zip-release@0.7.1
#       with:
#         type: 'zip'
#         filename: 'release.zip'
#         path: .
#         exclusions: '*.git*'

#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#            github_token: ${{ secrets.GITHUB_TOKEN }}
#            branch: main
#            message: 'Auto commit from github action'
        
#     - uses: vimtor/action-zip@v1
#       with:
#           files: ${{github.workspace}}
#           dest: result-${{ github.sha }}.zip
#     - name: push
#       uses: actions-x/commit@v6
        
        
#     - name: Commit & Push changes
#       uses: actions-js/push@master
#       with:
#         github_token: ${{ secrets.FULL_ACCESS }}
