name: Create Archive2
on: 
 push:
    branches: [ "main" ]
 workflow_dispatch:

env:
 Filename: Smart.approval4
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: main
    - name: Create local changes
      run: |
       # rm -r Function
       # mkdir ${{ github.workspace }}/Function
        zip ${{ env.Filename }}.zip ${{ github.workspace }}/* -x "*.git*"
        ls -lrt
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.MAVEN_TOKEN }}
      with:
        source_file: '${{ github.workspace }}/Function/${{ env.Filename }}.zip'
        destination_repo: 'kjs2021/maven'
        destination_folder: 'Function'
        destination_branch: test-branch
        user_email: 'kksaini6@yahoo.com'
        user_name: 'kjs2021'
        commit_message: '${{ env.Filename }}'   
